### ISSUE TITLE
Autobattle not turned on automatically.

### ISSUE THREAD

**Issue by EirikDaude** [HughJeffner/FFRK-LabMem#216] opened 2022-04-26 19:59 UTC
I started labmem a few hours ago, and when I came back I noticed it had become stuck on the first battle, because auto-battle wasn't enabled. Normally it notices this, and enables it - I don't know why it didn't happen this time.

Trying to disable autobattle a bit later, to see if it would be turned on automatically, led to the same issue occuring again. 

![bilde](https://user-images.githubusercontent.com/18211806/165381709-81f81bde-affb-4645-973b-8cdff5f64e74.png)

It is not a big problem, as I usually check in to see if the run is progressing as expected before leaving the house, but occassionally I forget.

**Comment by HughJeffner** [comment] 2022-04-28 13:19
Ah, I see what the problem is now.  When wait mode is enabled the party never gets defeated which triggers the auto battle check.  The (default) 15 minute battle timer restarts FFRK and the cycle repeats.

The auto battle check is somewhat 'expensive' so that's why it doesn't check at the start every battle.  I think a compromise may be to check it after the 15 minute battle timer.

**Comment by EirikDaude** [comment] 2022-04-28 13:44
Makes sense. Thanks for looking into it.

**Comment by HughJeffner** [comment] 2022-04-29 18:34
Alright I added this in 7.9 #218 

Planned to be released in the next week or so

**Closed by HughJeffner** 2022-04-29 18:34 UTC
Labels: bug
